/* ===========================
    Datos de las propiedades.
   =========================== */

const propiedades = [
    {
        id: 1,
        nombre: "Apartamento moderno en Alajuela",
        tipo: "Apartamento",
        provincia: "Alajuela",
        canton: "Alajuela Centro",
        precio: 350000,
        habitaciones: 2,
        banos: 1,
        metros: 48,
        etiquetas: ["Mascotas", "Cochera"],
        destacada: true,
        activa: true,
        imagen: "assets/images/prop-alajuela.png"
    },
    {
        id: 2,
        nombre: "Casa con jardín en Heredia",
        tipo: "Casa",
        provincia: "Heredia",
        canton: "San Rafael",
        precio: 600000,
        habitaciones: 3,
        banos: 2,
        metros: 100,
        etiquetas: ["Familias", "Cochera"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-heredia.png"
    },
    {
        id: 3,
        nombre: "Estudio compacto en San José",
        tipo: "Estudio",
        provincia: "San José",
        canton: "Barrio Escalante",
        precio: 185000,
        habitaciones: 1,
        banos: 1,
        metros: 35,
        etiquetas: ["Estudiantes"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-sanjose.png"
    },
    {
        id: 4,
        nombre: "Apartamento céntrico en Cartago",
        tipo: "Apartamento",
        provincia: "Cartago",
        canton: "El Guarco",
        precio: 280000,
        habitaciones: 2,
        banos: 1,
        metros: 50,
        etiquetas: ["Parejas"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-cartago.png"
    },
    {
        id: 5,
        nombre: "Apartamento Sky Garden",
        tipo: "Apartamento",
        provincia: "Heredia",
        canton: "San Rafael",
        precio: 420000,
        habitaciones: 2,
        banos: 2,
        metros: 65,
        etiquetas: ["Mascotas", "Parejas"],
        destacada: true,
        activa: true,
        imagen: "assets/images/prop-skygarden.png"
    },
    {
        id: 6,
        nombre: "Casa familiar en Escazú",
        tipo: "Casa",
        provincia: "San José",
        canton: "Escazú",
        precio: 850000,
        habitaciones: 4,
        banos: 3,
        metros: 150,
        etiquetas: ["Familias", "Cochera", "Mascotas"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-escazu.png"
    },
    {
        id: 7,
        nombre: "Estudio universitario en Liberia",
        tipo: "Estudio",
        provincia: "Guanacaste",
        canton: "Liberia",
        precio: 150000,
        habitaciones: 1,
        banos: 1,
        metros: 28,
        etiquetas: ["Estudiantes"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-liberia.png"
    },
    {
        id: 8,
        nombre: "Apartamento con vista en Curridabat",
        tipo: "Apartamento",
        provincia: "San José",
        canton: "Curridabat",
        precio: 470000,
        habitaciones: 2,
        banos: 2,
        metros: 72,
        etiquetas: ["Cochera", "Parejas"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-curridabat.png"
    },
    {
        id: 9,
        nombre: "Casa en condominio en Santa Ana",
        tipo: "Casa",
        provincia: "San José",
        canton: "Santa Ana",
        precio: 750000,
        habitaciones: 3,
        banos: 2,
        metros: 120,
        etiquetas: ["Familias", "Cochera"],
        destacada: false,
        activa: false,
        imagen: "assets/images/prop-santaana.png"
    },
    {
        id: 10,
        nombre: "Apartamento económico en Pérez Zeledón",
        tipo: "Apartamento",
        provincia: "San José",
        canton: "Pérez Zeledón",
        precio: 130000,
        habitaciones: 1,
        banos: 1,
        metros: 32,
        etiquetas: ["Estudiantes", "Parejas"],
        destacada: false,
        activa: true,
        imagen: "assets/images/prop-perezz.png"
    }
];